/**
 * apply-content.mjs
 * Applies NYT-quality headlines, clues, and context cards to puzzles.json.
 * Also replaces duplicate puzzles (IDs 89, 90) with new events from the editorial bible.
 * Run: node scripts/apply-content.mjs
 */
import { readFileSync, writeFileSync } from 'fs';
import { fileURLToPath } from 'url';
import { dirname, join } from 'path';

const __dirname = dirname(fileURLToPath(import.meta.url));
const root = join(__dirname, '..');
const puzzlesPath = join(root, 'data/puzzles.json');

// All content patches keyed by puzzle ID.
// clues: only the relevant day_of_week key is set; all others stay [].
// context_card: null = keep existing.
const PATCHES = {
  1: { headline: "The world's most famous prisoner walked free", clues: { tuesday: ["The Berlin Wall had fallen just months before", "South Africa was still three years from its first democratic election"] }, context_card: null },
  2: { headline: "Two astronauts left footprints where no one had walked", clues: { tuesday: ["Woodstock was just weeks away", "The Boeing 747 had not yet carried a single passenger"] }, context_card: null },
  3: { headline: "The unsinkable ship met its end", clues: { tuesday: ["The Panama Canal was still under construction", "Fenway Park opened the same week"] }, context_card: null },
  4: { headline: "Shots rang out in Dallas", clues: { wednesday: ["Martin Luther King Jr. had just delivered his most famous speech that summer", "The Beatles would land in America for the first time within three months"] }, context_card: null },
  5: { headline: "A quiet proposal rewired the planet", clues: { wednesday: ["The Exxon Valdez had just run aground in Alaska", "Nintendo's Game Boy went on sale that same spring"] }, context_card: "Tim Berners-Lee's original proposal at CERN was returned with the note: 'Vague, but exciting.' He wanted a way for physicists to share documents across different computers. The first web page went live in 1991, and Berners-Lee never patented his invention — he gave it away for free, insisting the web should belong to everyone." },
  6: { headline: "The world's worst nuclear accident", clues: { wednesday: ["The Space Shuttle Challenger had been lost earlier that same year", "Maradona's 'Hand of God' goal happened weeks later at the World Cup"] }, context_card: null },
  7: { headline: "The largest seaborne invasion in history", clues: { thursday: ["Roosevelt was serving an unprecedented third term as US president"] }, context_card: null },
  8: { headline: "A sleek rectangle replaced the keyboard", clues: { thursday: ["The final Harry Potter book was published that same summer"] }, context_card: null },
  9: { headline: "Five burglars caught inside a Washington office complex", clues: { thursday: ["Nixon had just returned from his historic visit to China that same year"] }, context_card: "The five men arrested inside the Democratic National Committee headquarters at 2:30 AM were carrying wiretapping equipment and $2,300 in sequential hundred-dollar bills. A security guard named Frank Wills noticed tape on a door lock and called the police. What began as a third-rate burglary unraveled into the greatest political scandal in American history, ending a presidency two years later." },
  10: { headline: "A single flash over a city ended an era of warfare", clues: { friday: ["Mussolini had been executed by partisans just months earlier"] }, context_card: null },
  11: { headline: "A red flag was lowered for the last time over the Kremlin", clues: { friday: ["The World Wide Web had just become publicly available that August"] }, context_card: null },
  12: { headline: "Twelve seconds above the sand dunes changed everything", clues: { friday: ["The first Tour de France was held that same summer"] }, context_card: null },
  13: { headline: "One pilot, one engine, and the whole Atlantic below", clues: { saturday: ["Jazz ruled the speakeasies and hemlines were rising"] }, context_card: null },
  14: { headline: "The world held its breath", clues: { saturday: ["Marilyn Monroe had sung 'Happy Birthday' to the president that summer"] }, context_card: null },
  15: { headline: "A quiet refusal that echoed across a nation", clues: { saturday: ["Rock and roll was new, Disneyland had just opened its gates"] }, context_card: null },
  16: { headline: "A plume of white smoke split into two against blue sky", clues: { sunday: [] }, context_card: null },
  17: { headline: "Two towers fell and a skyline was rewritten", clues: { sunday: [] }, context_card: null },
  18: { headline: "A date which will live in infamy", clues: { sunday: [] }, context_card: "The attack on Pearl Harbor lasted just under two hours but destroyed or damaged 19 Navy ships and 328 aircraft. Of the 2,403 Americans killed, nearly half died aboard the USS Arizona, which sank in nine minutes. Japan had intended to deliver a formal declaration of war before the attack, but the message arrived late — turning a military strike into something Americans would never forgive." },
  19: { headline: "A cosmonaut became the first to see Earth from above", clues: { monday: ["The Berlin Wall went up later that same summer", "A new American president had just taken office promising a New Frontier"] }, context_card: null },
  20: { headline: "The Bastille fell", clues: { monday: ["George Washington had just been inaugurated as the first US president", "Mozart was composing his last operas in Vienna"] }, context_card: null },
  21: { headline: "Thirteen colonies broke free", clues: { monday: ["Adam Smith published The Wealth of Nations the same year", "Captain Cook was on his third and final voyage"] }, context_card: "Thomas Jefferson drafted the Declaration of Independence in seventeen days. Congress made 86 changes to his draft, cutting roughly a quarter of the text — including a passage condemning the slave trade. The final document was signed by 56 men, many of whom knew they were signing what could become their death warrant." },
  22: { headline: "A quarter-million people stood before the Lincoln Memorial", clues: { tuesday: ["The Beatles released 'Please Please Me' earlier that year", "A nuclear test ban treaty was signed that same summer"] }, context_card: "The March on Washington was organized in just two months. King's most famous lines — 'I have a dream' — were partly improvised; gospel singer Mahalia Jackson shouted 'Tell them about the dream, Martin!' from behind him on the stage. The prepared text had no mention of dreams." },
  23: { headline: "A single symbol connected every mailbox on Earth", clues: { tuesday: ["Intel had just released its first microprocessor", "The Pentagon Papers were published in The New York Times that same year"] }, context_card: null },
  24: { headline: "Two Stanford students in a garage", clues: { tuesday: ["The Lewinsky scandal dominated American headlines", "Titanic was the year's biggest film at the box office"] }, context_card: null },
  25: { headline: "Everything would ship from one place — eventually", clues: { wednesday: ["Nelson Mandela had just been elected president of South Africa", "The first PlayStation launched in Japan that December"] }, context_card: null },
  26: { headline: "Life's blueprint revealed itself as a twisted ladder", clues: { wednesday: ["Edmund Hillary and Tenzing Norgay summited Everest weeks later", "Elizabeth II had just been crowned Queen of England"] }, context_card: null },
  27: { headline: "A mysterious immune disorder", clues: { wednesday: ["MTV broadcast its first music video that August", "The IBM personal computer went on sale for the first time"] }, context_card: null },
  28: { headline: "A surgeon placed a beating heart inside another man's chest", clues: { thursday: ["The Summer of Love had just swept through San Francisco"] }, context_card: "Christiaan Barnard performed the first human heart transplant in Cape Town on December 3, 1967, replacing the heart of Louis Washkansky with that of a young woman killed in a car accident. The operation took nine hours. Washkansky survived just eighteen days before dying of pneumonia — but Barnard had proved it could be done, and within a year, more than a hundred transplants followed worldwide." },
  29: { headline: "Parents wept with relief at the news from a university lab", clues: { thursday: ["Disneyland opened its gates in Anaheim that same summer"] }, context_card: "When Jonas Salk's polio vaccine was declared 'safe, effective, and potent' on April 12, 1955, church bells rang across America. Polio had paralyzed an average of 35,000 people each year during the early 1950s. Salk famously refused to patent the vaccine — when asked who owned it, he replied, 'The people. Could you patent the sun?'" },
  30: { headline: "A mold-covered petri dish changed medicine forever", clues: { thursday: ["Mickey Mouse made his first appearance on screen that same year"] }, context_card: "Alexander Fleming returned from holiday to find a petri dish contaminated by a mold that had killed the surrounding bacteria. He nearly threw it away. It took another decade and two other scientists — Florey and Chain — to turn his observation into a usable drug. By D-Day, there was enough penicillin to treat every wounded Allied soldier on the beaches of Normandy." },
  31: { headline: "A square frame changes how we see the world", clues: { friday: ["The iPad had just debuted earlier that same year"] }, context_card: "The app gained 25,000 users on its first day — before it even existed on Android. Built in eight weeks, it nearly launched under the name 'Burbn' before a pivot stripped everything except photo filters and sharing. Within two years, a billion-dollar acquisition made it the most expensive purchase-per-employee in tech history." },
  32: { headline: "Broadcast yourself", clues: { friday: ["Hurricane Katrina footage flooded the platform months after launch"] }, context_card: "The first video ever uploaded — 18 seconds of a man at the San Diego Zoo — set the tone for what would become the world's second-largest search engine. Three former payment-company employees built it above a pizzeria, and within 18 months sold it for $1.65 billion. The site now serves over a billion hours of video daily, more than broadcast television and Netflix combined." },
  33: { headline: "A volunteer army rewrites all human knowledge", clues: { friday: ["The dot-com bubble had just burst, leaving server space cheap"] }, context_card: "Its founder originally envisioned an expert-written encyclopedia called Nupedia, which produced exactly 12 articles in its first year. The pivot to open editing was meant as a feeder project, but within weeks the wiki had outpaced its parent. A 2005 Nature study found its science articles contained roughly the same error rate as Encyclopædia Britannica." },
  34: { headline: "Twelve nations abandon their money", clues: { saturday: ["A millennium's last quiet revolution, sealed before the champagne corks flew"] }, context_card: null },
  35: { headline: "A green-tinted screen conquers the schoolyard", clues: { saturday: ["Cold War concrete was crumbling in Europe while children everywhere stared down at their palms"] }, context_card: "Competitors offered color screens, backlighting, and superior processors — and lost. The device's designer deliberately chose outdated screen technology because it consumed so little power that four AA batteries lasted 30 hours. Bundled with a puzzle game from the Soviet Union, it sold 118 million units and proved that portability mattered more than performance." },
  36: { headline: "Wall Street's longest fall begins in a single afternoon", clues: { saturday: ["Talkies had just killed the silent film star; now silence fell on the trading floor"] }, context_card: "The ticker tape ran so far behind actual trades that brokers were selling stocks without knowing their real price. Sixteen million shares changed hands that day — a volume record that stood for nearly 40 years. The market wouldn't return to its pre-crash peak until 1954, a full quarter-century later." },
  37: { headline: "Eight hours of light etched onto pewter", clues: { sunday: [] }, context_card: "The exposure required roughly eight hours of direct sunlight, producing a grainy view of rooftops and a courtyard from an upstairs window in Burgundy. The inventor had been experimenting with light-sensitive bitumen for nearly a decade, failing repeatedly before this single surviving image. It now lives in a climate-controlled case at the University of Texas, so faded it can only be seen when lit at a precise angle." },
  38: { headline: "What hath God wrought", clues: { sunday: [] }, context_card: "The message traveled 40 miles from the Capitol in Washington to a railroad depot in Baltimore in less than a second — a speed that made newspaper editors openly anxious about the future of their profession. Within a decade, wire stretched across the continent; within two, it crossed the Atlantic Ocean floor." },
  39: { headline: "Movable type threatens every scribe in Europe", clues: { sunday: [] }, context_card: "The technology itself wasn't new — China had movable type four centuries earlier — but the innovation was combining it with a converted wine press, oil-based ink, and a metal alloy that could survive thousands of impressions. Within 50 years, an estimated 20 million volumes had been produced across Europe, more than all the scribes of the previous millennium combined." },
  40: { headline: "Fort Sumter bombarded", clues: { monday: ["Abraham Lincoln had been inaugurated just weeks before the first shots", "The Pony Express was still carrying mail across the western frontier"] }, context_card: "The 34-hour bombardment killed no one on either side — the only fatality came during the surrender ceremony, when a cannon exploded. The fort's commander had personally trained several of the Confederate officers now firing on him. Four years and 620,000 deaths later, he returned to raise the same flag he'd been forced to lower." },
  41: { headline: "A mystery illness circles the globe in waves", clues: { monday: ["The Great War was grinding through its final year in Europe", "Ragtime was giving way to early jazz in American dance halls"] }, context_card: "It killed more people in 24 weeks than HIV/AIDS killed in 24 years, yet wartime censorship kept it out of headlines in combatant nations — only neutral Spain reported freely, which is how a Kansas-origin virus got a Spanish name. The second wave struck healthy adults aged 20-40 hardest. Global death estimates range from 50 to 100 million, making the true toll permanently unknowable." },
  42: { headline: "A swiveling pelvis scandalizes sixty million viewers", clues: { monday: ["The Interstate Highway System had just been authorized by Congress", "The Hungarian Revolution was making front-page news that autumn"] }, context_card: "CBS cameras were ordered to film from the waist up, but the damage was already done — his appearance weeks earlier had drawn the largest television audience in history. He earned $50,000 for three appearances, a staggering sum for a 21-year-old truck driver from Mississippi. The host privately called him 'a decent, fine boy' while publicly declaring the performance unsuitable for family television." },
  43: { headline: "Golden arches appear", clues: { tuesday: ["Disneyland opened its gates in Anaheim that same summer", "Rosa Parks refused to give up her bus seat in Montgomery months later"] }, context_card: "The franchising salesman who built the empire wasn't the founder — he was a 52-year-old milkshake machine vendor who walked into a San Bernardino hamburger stand and saw the future. The original brothers had already perfected their 'Speedee Service System,' serving a burger in 30 seconds. He bought them out for $2.7 million; their handshake deal for ongoing royalties was never honored." },
  44: { headline: "The happiest place on Earth", clues: { tuesday: ["James Dean's final film was released that same year", "The Salk polio vaccine had just been declared safe months earlier"] }, context_card: "Opening day was such a disaster that insiders still call it 'Black Sunday' — temperatures hit 100°F, asphalt softened under women's heels, and counterfeit tickets doubled the crowd. A plumbers' strike forced a choice between working toilets and working water fountains; the creator chose toilets. The park recouped its entire $17 million construction cost within seven weeks." },
  45: { headline: "An eleven-inch doll arrives at the toy fair", clues: { tuesday: ["Alaska and Hawaii became states that same year", "Fidel Castro had just seized power in Havana weeks earlier"] }, context_card: "She was inspired by a German novelty doll originally marketed to adult men as a gag gift. The creator's male business partners all argued that mothers would never buy their daughters a doll with breasts; 300,000 sold in the first year. Her full name — Barbara Millicent Roberts — was never printed on a box." },
  46: { headline: "A bright yellow circle devours an entire industry", clues: { wednesday: ["The designer wanted to create something women and couples would play on dates", "The US boycotted that summer's Olympics in the host city"] }, context_card: "The original Japanese name was changed for Western markets because distributors feared vandals would alter the first letter. It earned $2.5 billion in quarters within its first 15 months. The kill screen on level 256, caused by an integer overflow, was not beaten legitimately until 1999." },
  47: { headline: "A plumber runs right and saves an industry", clues: { wednesday: ["The North American console market had collapsed two years prior and retailers refused to stock games", "Live Aid concerts raised millions for Ethiopian famine relief that same summer"] }, context_card: "The game was designed as the pack-in title for a console that retailers initially refused to carry. Its creator had no formal programming training and composed the music himself. The game sold 40 million copies — without internet distribution — and single-handedly resurrected a home entertainment industry that analysts had declared permanently dead." },
  48: { headline: "Falling shapes from behind the Iron Curtain", clues: { wednesday: ["Its creator worked at the Soviet Academy of Sciences and initially received no royalties", "George Orwell's dystopian year had just passed with surprising calm"] }, context_card: "The licensing rights became the subject of the most byzantine legal battle in gaming history — the Soviet government, a British software company, and multiple American publishers all claimed ownership simultaneously. Its designer earned nothing from the game's first decade of global sales. Cognitive scientists later discovered it literally changes brain structure, thickening the cortex in regions governing spatial reasoning." },
  49: { headline: "A disc-based console disrupts cartridge gaming", clues: { thursday: ["The console was born from a failed partnership with its future rival's cartridge-based system"] }, context_card: "It began as a CD-ROM add-on for a competitor's console, but the partnership collapsed in a public betrayal at a trade show. The jilted partner channeled that anger into a standalone machine that used cheaper disc media, undercut the competition by $100, and sold over 100 million units — inaugurating a new era of 3D gaming that made sprites feel instantly obsolete." },
  50: { headline: "A software giant builds its first console", clues: { thursday: ["The September 11 attacks delayed the console's European launch by months"] }, context_card: "The machine was essentially a stripped-down PC running a custom operating system, which horrified gaming purists. Internal memos reveal the company lost an estimated $125 on every unit sold, treating the entire venture as a $4 billion bet to control the living room. Its online service, bundled with an Ethernet port when competitors still used dial-up, would eventually reshape how the entire industry thought about multiplayer gaming." },
  51: { headline: "1,000 songs in your pocket", clues: { thursday: ["Portable MP3 players already existed, but this one used a tiny hard drive from a Japanese manufacturer"] }, context_card: "Critics mocked the $399 price tag — 'no wireless, less space than a Nomad, lame,' read the most famous review. The device accounted for less than 2% of the company's revenue in its first year. Within six years it would generate half the company's income and lead directly to the product that would make it the world's most valuable corporation." },
  52: { headline: "Mail-order movies pivot to instant delivery", clues: { friday: ["The first iPhone shipped that same summer, giving streaming a mobile future"] }, context_card: "The streaming library at launch contained just 1,000 titles — less than a single Blockbuster store. The company had offered to sell itself to its brick-and-mortar rival for $50 million three years earlier and been laughed out of the room. That rival filed for bankruptcy three years after streaming launched; the streamer is now worth more than $150 billion." },
  53: { headline: "Every song ever recorded, free and legal", clues: { friday: ["The global financial crisis was unfolding as the service launched in Sweden"] }, context_card: "It launched in invitation-only mode in a single European country, paying fractions of a cent per stream while the music industry was still prosecuting teenagers for illegal downloads. Major labels initially licensed their catalogs only because they were desperate — CD sales had fallen by half in a decade. The model musicians mocked as 'paying in pennies' now generates more revenue for the recording industry than CDs ever did at their peak." },
  54: { headline: "A dorm-room directory goes live", clues: { friday: ["Gmail launched in invitation-only beta that same year"] }, context_card: "Registration required a valid university email address, and the site spread campus by campus — a deliberate scarcity strategy that created desperate demand at schools not yet invited. Within 24 hours of launching at each new university, more than half the student body had signed up. The founder was 19 years old, running the servers from his dormitory room." },
  55: { headline: "What are you doing?", clues: { saturday: ["A 140-character whisper that turned every phone into a printing press"] }, context_card: "The original prototype was built in two weeks as a side project at a podcasting startup, and the first message — 'just setting up my twttr' — had all the grandeur of a throat-clearing cough. The 140-character limit was dictated by SMS technology, not philosophy. It would take an earthquake in Haiti, an uprising in Tehran, and an Arab Spring to reveal what a short-message platform could actually become." },
  56: { headline: "Messages that self-destruct after viewing", clues: { saturday: ["Born in a world where every photo was forever, promising that nothing had to be"] }, context_card: "Every investor said an app built on impermanence was fundamentally worthless. A major social network offered $3 billion in cash to acquire it; the 23-year-old CEO declined. The feature everyone assumed was designed for sexting turned out to be what teenagers actually wanted: a way to communicate without building a permanent, searchable archive of their adolescence." },
  57: { headline: "A pseudonym publishes a blueprint for digital cash", clues: { saturday: ["Lehman Brothers had collapsed weeks before, and trust in banks was at a generational low"] }, context_card: "The nine-page paper was posted to an obscure cryptography mailing list and received almost no attention. Embedded in the code of the first-ever block was a headline from The Times of London about bank bailouts — a quiet political statement disguised as a timestamp. The author vanished completely in 2011, leaving behind roughly one million tokens now worth tens of billions, never moved from their original addresses." },
  58: { headline: "Programmable money expands the blockchain's ambitions", clues: { sunday: [] }, context_card: "Its creator was a 21-year-old college dropout who decided the original digital currency was too limited — like a calculator when the world needed a computer. He funded the project through a public token sale that raised $18 million in digital currency. The platform's name was chosen from a list of science fiction concepts found on Wikipedia." },
  59: { headline: "A digital token claims ownership of art", clues: { sunday: [] }, context_card: "The first known experiment linked a short animation to a blockchain entry and declared it a unique, ownable digital object — a concept that sounded absurd to anyone who understood how copying a file works. The technology languished in obscurity for years before a $69 million auction made the art world pay attention in 2021. The inevitable crash wiped out 95% of values within two years." },
  60: { headline: "Three small ships reach a hemisphere unknown to Europe", clues: { sunday: [] }, context_card: "The navigator died believing he had reached Asia, never acknowledging the continental landmass his voyages had revealed to European mapmakers. The Taíno people he encountered had inhabited the Caribbean for at least 1,500 years. Within 50 years of first contact, disease, enslavement, and violence had reduced the Taíno population from an estimated 250,000 to fewer than 500." },
  61: { headline: "A king forced to kneel before his barons", clues: { monday: ["The Crusades were still being fought in the Holy Land", "Oxford University had already been teaching for decades"] }, context_card: "The meadow at Runnymede was chosen because neither side trusted the other enough to meet indoors. King John sealed the charter under duress, then immediately asked the Pope to annul it — which he did within ten weeks. The document failed as a peace treaty but survived as the foundation of constitutional law across the English-speaking world." },
  62: { headline: "A glover's son who would remake the English language", clues: { monday: ["Elizabeth I had recently been crowned queen", "Galileo was a newborn in Pisa"] }, context_card: "Born in a market town best known for its wool trade, the playwright received a solid grammar school education but never attended university — a fact his rivals never let him forget. He would go on to invent over 1,700 English words, from 'assassination' to 'lonely.' His father made gloves; his son died at eleven." },
  63: { headline: "A space opera that studio executives expected to flop", clues: { monday: ["Jimmy Carter was in his first year as US president", "The Apple II personal computer went on sale that same year"] }, context_card: "Twentieth Century Fox was so certain the film would fail that it let the director keep merchandising rights — a decision that would cost the studio billions. Shot partly in the Tunisian desert, where a nearby Libyan military operation nearly shut down production, it earned $461 million worldwide and redefined what a movie could sell." },
  64: { headline: "A mechanical shark that kept breaking down", clues: { tuesday: ["The Watergate scandal had just forced a president to resign", "Saturday Night Live premiered on NBC that same fall"] }, context_card: "The mechanical shark malfunctioned so often that the young director was forced to hide it, showing only glimpses — a constraint that accidentally invented modern suspense filmmaking. Beaches across America emptied that summer despite record heat. The film's success created the template every studio still follows: wide release, massive marketing, summer launch." },
  65: { headline: "Phone home", clues: { tuesday: ["The Falklands War was being fought that same spring", "Michael Jackson's Thriller album was released later that year"] }, context_card: "The film was born from loneliness — the director conceived it while imagining an imaginary friend after his parents' divorce. M&M's famously declined a product placement deal, so the production used Reese's Pieces instead, tripling the candy's sales overnight. It became the highest-grossing film in history, a record it held for eleven years." },
  66: { headline: "Dinosaurs return", clues: { tuesday: ["The European Union was formally established that same year", "Nirvana's In Utero album was released weeks later"] }, context_card: "The novel's team pivoted from animatronics to an untested technique — computer-generated imagery for living creatures. The result — six minutes of CGI dinosaurs in a two-hour film — convinced every studio in Hollywood that practical effects were finished. The paleontology department at many universities saw enrollment double within a year." },
  67: { headline: "What is the Matrix?", clues: { wednesday: ["The Y2K bug had the world bracing for digital collapse", "The euro currency was introduced to financial markets that January"] }, context_card: "The directors pitched the film with a comic book because no studio could visualize what they were describing. Every lead actor in Hollywood turned down the role before it was offered to a star best known for action comedies. The 'bullet time' effect required 120 still cameras firing in sequence — borrowed from a 19th-century photographer who used it to study galloping horses." },
  68: { headline: "An alien world rendered in a wavelength the eye cannot see", clues: { wednesday: ["Barack Obama had just been inaugurated as US president", "The world was deep in the worst financial crisis since the Great Depression"] }, context_card: "The director waited fourteen years to make the film because the technology he needed did not exist yet. When it finally opened, it earned a billion dollars in just seventeen days. Its pioneering 3D technology was supposed to transform cinema forever; within five years, audiences had largely abandoned the format." },
  69: { headline: "Music escapes the living room", clues: { wednesday: ["Margaret Thatcher had just become Britain's first female prime minister", "The Soviet Union had recently invaded Afghanistan"] }, context_card: "The device was rejected by every division inside the company before one engineer championed it. Its co-creator was so impatient with the prototype that he dunked it in an aquarium — when bubbles rose, he declared there was still space inside to make it smaller. It sold 200 million units and turned headphones from studio equipment into street fashion." },
  70: { headline: "A cassette tape that won the format war", clues: { thursday: ["The United States was celebrating its bicentennial"] }, context_card: "The format war between VHS and its rival Betamax had nothing to do with quality — Betamax was technically superior. VHS won because its tapes could record for two hours, long enough to capture a full movie, while Betamax initially maxed out at one. The adult film industry's early adoption of VHS may have tipped the balance, though the companies involved have always denied it." },
  71: { headline: "A silver disc that promised perfect sound forever", clues: { thursday: ["The Falklands War dominated the news that spring"] }, context_card: "The disc's diameter — 12 centimeters — was allegedly chosen so it could hold all of Beethoven's Ninth Symphony without interruption. Early players cost more than $700, and only about fifty albums were available at launch. The format would eventually kill the vinyl record, then be killed itself by the MP3." },
  72: { headline: "You press the button", clues: { thursday: ["Jack the Ripper was terrorizing London's East End"] }, context_card: "The founder's slogan was 'You press the button, we do the rest' — and he meant it literally. The camera came preloaded with a 100-exposure roll; when finished, customers mailed the entire device back to the factory. It democratized photography by removing every technical barrier, turning a specialist craft into a household habit." },
  73: { headline: "Sixty seconds from shutter click to finished print", clues: { friday: ["The Berlin Airlift was keeping a city alive that same year"] }, context_card: "The inventor's three-year-old daughter asked why she couldn't see the photo he had just taken of her — and that question launched a billion-dollar company. The first camera weighed nearly four pounds and produced sepia-toned prints that had to be coated with fixative by hand. Andy Warhol would later make the instant photograph an art form, carrying one everywhere he went." },
  74: { headline: "An image captured without film for the first time", clues: { friday: ["The Vietnam War had just ended with the fall of Saigon"] }, context_card: "The prototype weighed eight pounds, took 23 seconds to record an image, and produced a 0.01 megapixel black-and-white photograph. The engineer who built it presented his invention to corporate leadership, who told him to bury it: the company's entire business was built on selling film. Three decades later, that same company filed for bankruptcy because digital photography had destroyed its market." },
  75: { headline: "Any color, as long as it's black", clues: { friday: ["The Wright brothers' first flight was still recent memory"] }, context_card: "The assembly line did not start with the car — it started with the price. The founder was obsessed with making a car cheap enough for his own factory workers to buy, and the moving assembly line was simply the method that got the price from $850 down to $260. By the time production ended, half of all cars on American roads were the same model." },
  76: { headline: "A ticket sold for five dollars, destination: the sky", clues: { saturday: ["The old world was about to tear itself apart"] }, context_card: "The flight lasted 23 minutes, covered 21 miles across a bay, and the only passenger was the mayor of the destination city, who had won the seat at auction. The pilot made the trip twice daily for four months before the airline folded — there simply were not enough passengers. It would take another decade before commercial aviation became a real industry." },
  77: { headline: "A beeping sphere that changed everything it touched", clues: { saturday: ["Leave It to Beaver was America's picture of itself"] }, context_card: "The satellite was the size of a beach ball and carried no scientific instruments — it could only transmit a simple radio pulse. But that beep, picked up by amateur radio operators worldwide, proved that the rival superpower had rockets powerful enough to reach any city on Earth. Within a year, the stunned response produced NASA, a new science curriculum for American schools, and the modern concept of the technology race." },
  78: { headline: "An eye opened above the atmosphere", clues: { saturday: ["The wall between East and West had just crumbled"] }, context_card: "The telescope was delivered to orbit with a flaw in its primary mirror — a manufacturing error of just 2.2 micrometers, about one-fiftieth the width of a human hair. For three years it sent back blurry images. Astronauts installed corrective optics during a spacewalk, and the telescope went on to fundamentally change humanity's understanding of the age and size of the universe." },
  79: { headline: "A small rover rolls across red dust", clues: { sunday: [] }, context_card: "The rover was the size of a microwave oven and was designed to last seven days. It lasted eighty-three. Named through a student essay contest, the little machine analyzed rocks and sent back 2.3 billion bits of data, proving Mars had once been warm and wet. The mission cost less than the production budget of a Hollywood blockbuster released that same summer." },
  80: { headline: "Movable type sets the world in motion", clues: { sunday: [] }, context_card: "The printer was nearly bankrupt before the first Bible rolled off his press — he had borrowed heavily and his investor eventually sued him, seizing the equipment. The original print run was about 180 copies, of which 49 survive today, each worth tens of millions of dollars. Within fifty years, an estimated twenty million volumes had been printed across Europe, ending the Church's monopoly on knowledge." },
  81: { headline: "The last emperor removed his purple robes", clues: { sunday: [] }, context_card: "The final emperor was a teenager, installed as a puppet by his father, a Germanic general who actually held the power. The barbarian king who deposed him did not even bother to claim the title — he simply sent the imperial regalia to Constantinople and declared the western office unnecessary. The eastern half of the empire would continue for nearly another thousand years." },
  82: { headline: "A bakery fire that remade a capital city", clues: { monday: ["The Great Plague had devastated the same city just a year before", "Isaac Newton was a young student developing his theory of gravity"] }, context_card: "The fire began in a bakery on Pudding Lane shortly after midnight and burned for four days, destroying 13,200 houses, 87 churches, and old St Paul's Cathedral. Remarkably, only six verified deaths were recorded. The architect appointed to rebuild the city designed 51 new churches, including a cathedral that took 35 years to complete." },
  83: { headline: "Seventy-three million Americans watched four musicians play", clues: { monday: ["The president had been assassinated just weeks before", "Martin Luther King Jr. would receive the Nobel Peace Prize later that year"] }, context_card: null },
  84: { headline: "Half a million people gathered on a dairy farm", clues: { monday: ["Humans had walked on the moon just weeks earlier", "Richard Nixon was in his first year as president"] }, context_card: "The festival was supposed to happen in a different town entirely — the original site pulled the permit a month before the event. A dairy farmer agreed to lease his land, and within weeks his alfalfa field became a temporary city with no fences and no way to collect tickets. The promoters lost over a million dollars. The farmer said he would do it again." },
  85: { headline: "Two stages, two continents, one satellite link", clues: { tuesday: ["A hole in the ozone layer was discovered that same year", "Nintendo released its first home console in North America that October"] }, context_card: "The concert was organized in ten weeks — an impossibly short timeline for an event broadcast live to 1.9 billion people across 150 countries. The London and Philadelphia stages ran simultaneously, connected by satellite. It raised $127 million for famine relief, but its lasting impact was proving that television could turn a concert into a global event and shame governments into action." },
  86: { headline: "I want my MTV", clues: { tuesday: ["The first Space Shuttle mission launched that same spring", "Prince Charles married Lady Diana that summer"] }, context_card: "The first video ever played was a deliberate joke — a song about how television had disrupted an earlier medium. At launch, the channel could only be received in a few thousand homes in New Jersey. Record labels initially refused to provide videos, so the same handful of clips ran on heavy rotation for months. Within three years, an artist's visual image had become as important as their sound." },
  87: { headline: "Eighteen million songs, available for free, overnight", clues: { tuesday: ["The Y2K bug dominated headlines that December", "The Sopranos had just premiered on HBO"] }, context_card: "Two college freshmen built the service in a dorm room, and within a year it had more users than most countries have people. The recording industry sued, calling it the biggest threat to copyright since the photocopier. The legal battle shut it down, but the damage was done — an entire generation had learned that music could be free, and the industry spent the next decade trying to unlearn that lesson." },
  88: { headline: "99 cents per song", clues: { wednesday: ["The US had invaded Iraq weeks earlier", "The Human Genome Project was completed that same spring"] }, context_card: "The music industry had spent four years suing teenagers and losing the public relations battle when a tech company proposed a radical idea: make buying music easier than stealing it. The store sold one million songs in its first five days. Within six years, it was the largest music retailer in the United States, and CDs were relics." },
};

// Replacement puzzles for IDs 89 and 90 (replacing Spotify/iPhone duplicates)
const REPLACEMENTS = {
  89: {
    event: "The Berlin Wall Falls",
    event_formal: "Fall of the Berlin Wall",
    year: 1989,
    day_of_week: "wednesday",
    headline: "A concrete barrier crumbles under the weight of a crowd",
    tier: 1,
    difficulty_rating: 4,
    clues: { wednesday: ["The Tiananmen Square protests had been crushed just months before", "The first episode of The Simpsons aired that December"] },
    context_card: "For 28 years, Checkpoint Charlie was the defining symbol of the Cold War. On November 9th, 1989, a confused bureaucrat announced that East Germans could cross freely — and thousands flooded through. No one had planned the announcement. The wall fell because the system was already crumbling.",
  },
  90: {
    event: "World War I Begins",
    event_formal: "Outbreak of World War I",
    year: 1914,
    day_of_week: "wednesday",
    headline: "An archduke's assassination echoes across a continent",
    tier: 1,
    difficulty_rating: 6,
    clues: { wednesday: ["The Panama Canal had just opened for business", "Charlie Chaplin made his first film appearance that same year"] },
    context_card: "The assassination of Archduke Franz Ferdinand in Sarajevo on June 28, 1914, set off a chain reaction of alliance obligations. What was supposed to be a short war became a four-year conflict that killed 17 million people and destroyed four empires: the German, Austro-Hungarian, Ottoman, and Russian empires.",
  },
};

// Build the base clues structure
function buildClues(dayKey, clueValues) {
  const base = { monday: [], tuesday: [], wednesday: [], thursday: [], friday: [], saturday: [], sunday: [] };
  if (dayKey && clueValues) base[dayKey] = clueValues;
  return base;
}

// Load and apply patches
const data = JSON.parse(readFileSync(puzzlesPath, 'utf-8'));
let patched = 0;
let replaced = 0;

for (const puzzle of data.puzzles) {
  const rep = REPLACEMENTS[puzzle.id];
  if (rep) {
    // Full replacement
    puzzle.event = rep.event;
    puzzle.event_formal = rep.event_formal;
    puzzle.year = rep.year;
    puzzle.day_of_week = rep.day_of_week;
    puzzle.headline = rep.headline;
    puzzle.tier = rep.tier;
    puzzle.difficulty_rating = rep.difficulty_rating;
    puzzle.clues = buildClues(rep.day_of_week, rep.clues[rep.day_of_week]);
    puzzle.context_card = rep.context_card;
    replaced++;
    continue;
  }

  const patch = PATCHES[puzzle.id];
  if (!patch) continue;

  puzzle.headline = patch.headline;
  // Merge clues: set the relevant day, leave others as []
  const clueEntries = Object.entries(patch.clues);
  if (clueEntries.length > 0) {
    const [dayKey, values] = clueEntries[0];
    puzzle.clues = buildClues(dayKey, values);
  }
  if (patch.context_card !== null) {
    puzzle.context_card = patch.context_card;
  }
  patched++;
}

writeFileSync(puzzlesPath, JSON.stringify(data, null, 2) + '\n', 'utf-8');
console.log(`Patched ${patched} puzzles, replaced ${replaced} duplicate puzzles.`);

// Verify clues coverage
const noClues = data.puzzles.filter(p => {
  const day = p.day_of_week;
  if (day === 'sunday') return false; // Sunday has no clues by design
  const arr = p.clues[day];
  return !arr || arr.length === 0;
});
if (noClues.length === 0) {
  console.log('✓ All non-Sunday puzzles have clues.');
} else {
  console.log(`⚠ ${noClues.length} non-Sunday puzzles still missing clues:`);
  for (const p of noClues) console.log(`  ID ${p.id} [${p.day_of_week}]: ${p.event}`);
}
